# Generated by Django 3.1.6 on 2021-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sentence', models.CharField(default='null', max_length=1000)),
                ('language', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='equity_private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker_Date_Language', models.CharField(default='null', max_length=50)),
                ('Short_Name', models.CharField(default='null', max_length=50)),
                ('Full_Name', models.CharField(default='null', max_length=50)),
                ('Industry', models.CharField(default='null', max_length=50)),
                ('Founded', models.IntegerField(default='null')),
                ('Website', models.CharField(default='null', max_length=50)),
                ('Total_assets', models.IntegerField(default='null')),
                ('Net_Income', models.IntegerField(default='null', verbose_name='Income')),
                ('Date', models.DateTimeField()),
                ('url', models.CharField(default='null', max_length=50)),
                ('Youtube', models.CharField(default='null', max_length=50)),
                ('Podcast', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='equity_public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker_Date_Language', models.CharField(default='null', max_length=50)),
                ('Ticker', models.CharField(default='null', max_length=50)),
                ('Name', models.CharField(default='null', max_length=50)),
                ('Industry', models.CharField(default='null', max_length=50)),
                ('Founded', models.IntegerField(default='null')),
                ('Total_assets', models.IntegerField(default='null')),
                ('Net_income', models.IntegerField(default='null')),
                ('ClosePrice', models.IntegerField(default='null', verbose_name='Close Price')),
                ('Beta', models.IntegerField(default='null')),
                ('Market_Cap', models.IntegerField(default='null')),
                ('Float', models.IntegerField(default='null')),
                ('Outstanding_Shares', models.IntegerField(default='null')),
                ('ADV_10d', models.IntegerField(default='null')),
                ('Insider_Shares', models.IntegerField(default='null')),
                ('Institutional_Shares', models.IntegerField(default='null')),
                ('Date', models.DateTimeField()),
                ('url', models.CharField(default='null', max_length=50)),
                ('Youtube', models.CharField(default='null', max_length=50)),
                ('Podcast', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Category_Language', models.CharField(default='null', max_length=50)),
                ('language', models.CharField(default='null', max_length=50)),
                ('Category', models.CharField(default='null', max_length=50)),
                ('SubCategory', models.CharField(default='null', max_length=50)),
                ('Short_Description', models.CharField(default='null', max_length=250)),
                ('Description', models.CharField(default='null', max_length=500)),
                ('url', models.CharField(default='null', max_length=50)),
                ('Youtube', models.CharField(default='null', max_length=50)),
                ('Podcast', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Language', models.CharField(default='null', max_length=50)),
                ('Date', models.DateTimeField()),
                ('Category', models.CharField(default='null', max_length=50)),
                ('SubCategory', models.CharField(default='null', max_length=50)),
                ('FileName', models.CharField(default='null', max_length=50)),
                ('Description', models.CharField(default='null', max_length=500)),
                ('url', models.CharField(default='null', max_length=50)),
                ('Youtube', models.CharField(default='null', max_length=50)),
                ('Podcast', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='money_making_investing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Company', models.CharField(default='null', max_length=50)),
                ('Short_Name', models.CharField(default='null', max_length=50)),
                ('Full_Name', models.CharField(default='null', max_length=50)),
                ('Private_Public', models.CharField(default='null', max_length=50, verbose_name='Private-Public')),
                ('Entry', models.DateTimeField()),
                ('Exit', models.DateTimeField()),
                ('Strategy', models.CharField(default='null', max_length=50)),
                ('Position', models.IntegerField(default='null')),
                ('url', models.CharField(default='null', max_length=50)),
                ('Youtube', models.CharField(default='null', max_length=50)),
                ('Podcast', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='money_making_trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Play', models.CharField(default='null', max_length=50)),
                ('Date', models.DateTimeField()),
                ('Play', models.CharField(default='null', max_length=50)),
                ('Plan', models.CharField(default='null', max_length=50)),
                ('Outcome', models.CharField(default='null', max_length=50)),
                ('url', models.CharField(default='null', max_length=50)),
                ('Youtube', models.CharField(default='null', max_length=50)),
                ('Podcast', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('email', models.CharField(default='null', max_length=50)),
                ('phone', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='null', max_length=50)),
                ('Brand', models.CharField(default='null', max_length=50)),
                ('url', models.CharField(default='null', max_length=50)),
                ('language', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
