# Generated by Django 3.2.6 on 2022-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='analytical_apps_trade_journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sentence', models.TextField(blank=True)),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Analytical Apps Trade Journal',
                'verbose_name_plural': 'Analytical Apps Trade Journal',
            },
        ),
    ]
