# Generated by Django 3.2.6 on 2022-02-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='Date',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
