# Generated by Django 3.1.6 on 2021-09-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='Name',
            field=models.CharField(default='null', max_length=50, verbose_name='name'),
        ),
    ]
