# Generated by Django 3.2.6 on 2022-03-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220305_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_making_investing',
            name='Initial_Inv',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Outcome',
            field=models.IntegerField(blank=True),
        ),
    ]
