# Generated by Django 3.2.6 on 2022-03-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_analytical_apps_trade_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Description', models.CharField(blank=True, default='none', max_length=5100)),
                ('Newsletter', models.CharField(blank=True, max_length=1100)),
                ('Youtube', models.CharField(blank=True, max_length=1100)),
                ('Podcast', models.CharField(blank=True, max_length=1100)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
            },
        ),
    ]
