# Generated by Django 3.1.6 on 2021-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210908_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='Date',
            field=models.DateField(),
        ),
    ]
