# Generated by Django 3.2.6 on 2022-03-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_market_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='Country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='Language',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='market',
            name='Podcast',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='market',
            name='Product',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='market',
            name='YouTube',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
