# Generated by Django 3.1.6 on 2021-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210908_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='Language',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
