# Generated by Django 3.2.6 on 2022-03-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220305_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_making_investing',
            name='ROI',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
