# Generated by Django 3.2.6 on 2022-03-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_news_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoURL', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Home Video',
                'verbose_name_plural': 'Home Video',
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
