# Generated by Django 3.1.6 on 2021-09-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_market_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='language',
            new_name='Language',
        ),
        migrations.AddField(
            model_name='equity_private',
            name='Language',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='equity_public',
            name='Language',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
