# Generated by Django 3.2.6 on 2022-03-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220322_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscribers',
            options={'verbose_name': 'Contacts', 'verbose_name_plural': 'Contacts'},
        ),
    ]
