# Generated by Django 3.2.6 on 2022-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_money_making_investing_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_making_investing',
            name='ROI',
            field=models.FloatField(blank=True),
        ),
    ]
