# Generated by Django 3.1.6 on 2021-09-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210908_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity_public',
            name='Date',
            field=models.DateField(),
        ),
    ]
