# Generated by Django 3.2.6 on 2022-03-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_money_making_investing_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_making_investing',
            name='ReCap',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='ReCap',
            field=models.URLField(),
        ),
    ]
