# Generated by Django 3.1.6 on 2021-09-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210908_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity_private',
            name='Ticker',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
