# Generated by Django 3.2.6 on 2022-03-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_money_making_investing_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_making_investing',
            name='ROI',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
