# Generated by Django 3.2.6 on 2022-03-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220308_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='Research',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Research',
            field=models.URLField(),
        ),
    ]
