# Generated by Django 3.1.6 on 2021-09-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210908_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='SubCategory',
        ),
    ]
