# Generated by Django 3.2.6 on 2022-03-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220308_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='Research',
            field=models.URLField(),
        ),
    ]
