# Generated by Django 3.1.6 on 2021-09-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_learning_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='Short_Description',
        ),
    ]
