# Generated by Django 3.1.6 on 2021-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_learning_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='Short_Description',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='learning',
            name='SubCategory',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
