# Generated by Django 3.1.6 on 2021-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210908_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_making_investing',
            name='Date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Entry',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Exit',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Date',
            field=models.DateField(blank=True),
        ),
    ]
