# Generated by Django 3.1.6 on 2021-09-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210908_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='Date',
            field=models.DateField(blank=True),
        ),
    ]
