# Generated by Django 3.2.3 on 2021-09-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210908_2054'),
        ('base', '0012_auto_20210908_2106'),
    ]

    operations = [
    ]
