# Generated by Django 3.2.3 on 2021-09-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_aboutus_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_Name', models.CharField(default='null', max_length=100)),
                ('Child_Name', models.CharField(default='null', max_length=100)),
                ('Main_Child', models.CharField(default='null', max_length=100)),
                ('url', models.CharField(default='null', max_length=255)),
                ('Language', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
