# Generated by Django 3.2.3 on 2021-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_listpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='SocialMedia/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
