# Generated by Django 3.2.3 on 2021-09-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='Sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Founded',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Industry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Net_Income',
            field=models.IntegerField(blank=True, verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Podcast',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Short_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Ticker',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Ticker_Date_Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Total_assets',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Website',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='Youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_private',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='ADV_10d',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Beta',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='ClosePrice',
            field=models.IntegerField(blank=True, verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Float',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Founded',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Industry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Insider_Shares',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Institutional_Shares',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Market_Cap',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Net_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Outstanding_Shares',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Podcast',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Ticker',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Ticker_Date_Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Total_assets',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='Youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equity_public',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Date_Category_Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Podcast',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Short_Description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='learning',
            name='SubCategory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learning',
            name='Youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learning',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='Child_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='Main_Child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='Menu_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='url',
            field=models.FileField(upload_to='PDF'),
        ),
        migrations.AlterField(
            model_name='market',
            name='Category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='Date_Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='Description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='market',
            name='FileName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='Language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='Podcast',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='SubCategory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='Youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Date_Company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Podcast',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Position',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Private_Public',
            field=models.CharField(blank=True, max_length=50, verbose_name='Private-Public'),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Short_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Strategy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Date_Play',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Outcome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Plan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Play',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Podcast',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='Brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='Name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='table',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
