# Generated by Django 3.2.3 on 2021-09-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20210909_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='url',
            field=models.URLField(),
        ),
    ]
