# Generated by Django 3.2.3 on 2021-09-09 01:18

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_table_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_making_investing',
            name='Language',
            field=models.CharField(blank=True, default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='money_making_trading',
            name='Language',
            field=models.CharField(blank=True, default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='learning',
            name='url',
            field=models.FileField(upload_to=base.models.path_learning),
        ),
        migrations.AlterField(
            model_name='market',
            name='url',
            field=models.FileField(upload_to=base.models.market_path),
        ),
    ]
