# Generated by Django 3.2.3 on 2021-09-09 01:42

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210909_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_making_investing',
            name='url',
            field=models.FileField(upload_to=base.models.path_money_making_investing),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='url',
            field=models.FileField(upload_to=base.models.path_money_making_trading),
        ),
    ]
