# Generated by Django 3.2.3 on 2021-09-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20210909_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='Category',
            new_name='Filename',
        ),
        migrations.RenameField(
            model_name='learning',
            old_name='SubCategory',
            new_name='via',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='Short_Description',
        ),
    ]
