# Generated by Django 3.2.3 on 2021-09-09 11:03

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20210909_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker_Date_Language', models.CharField(blank=True, max_length=50)),
                ('Ticker', models.CharField(blank=True, max_length=50)),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Industry', models.CharField(blank=True, max_length=50)),
                ('Founded', models.IntegerField(blank=True)),
                ('Total_assets', models.IntegerField(blank=True)),
                ('Net_income', models.IntegerField(blank=True)),
                ('ClosePrice', models.IntegerField(blank=True, verbose_name='Close Price')),
                ('Beta', models.IntegerField(blank=True)),
                ('Market_Cap', models.IntegerField(blank=True)),
                ('Float', models.IntegerField(blank=True)),
                ('Outstanding_Shares', models.IntegerField(blank=True)),
                ('ADV_10d', models.IntegerField(blank=True)),
                ('Insider_Shares', models.IntegerField(blank=True)),
                ('Institutional_Shares', models.IntegerField(blank=True)),
                ('Date', models.DateField()),
                ('url', models.FileField(upload_to=base.models.path_equity)),
                ('Youtube', models.CharField(blank=True, max_length=50)),
                ('Podcast', models.CharField(blank=True, max_length=50)),
                ('equity_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('Language', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='equity_private',
        ),
        migrations.DeleteModel(
            name='equity_public',
        ),
    ]
