# Generated by Django 3.2.3 on 2021-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20210909_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='height',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='width',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
