# Generated by Django 3.2.3 on 2021-09-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20210910_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='Website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
