# Generated by Django 3.2.3 on 2021-09-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_equity_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equity',
            old_name='equity_type',
            new_name='Equity_Type',
        ),
        migrations.RenameField(
            model_name='learning',
            old_name='Filename',
            new_name='File_Name',
        ),
    ]
