# Generated by Django 3.2.3 on 2021-09-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20210910_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='File_Name',
            new_name='FileName',
        ),
    ]
