# Generated by Django 3.2.3 on 2021-09-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_analytics_apps_market_mover_analytics_apps_stock_picker_analytics_apps_systematic_trad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpage',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
