# Generated by Django 3.2.3 on 2021-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_listpage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics_apps_company_prospecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sentence', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
