# Generated by Django 2.2.4 on 2021-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_analytics_apps_company_prospecting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='analytics_apps_company_prospecting',
            options={'verbose_name': 'Analytics Apps Company Prospecting', 'verbose_name_plural': 'Analytics Apps Company Prospecting'},
        ),
        migrations.AlterModelOptions(
            name='analytics_apps_market_mover',
            options={'verbose_name': 'Analytics Apps Market Mover', 'verbose_name_plural': 'Analytics Apps Market Mover'},
        ),
        migrations.AlterModelOptions(
            name='analytics_apps_stock_picker',
            options={'verbose_name': 'Analytics Apps Stock Picker', 'verbose_name_plural': 'Analytics Apps Stock Picker'},
        ),
        migrations.AlterModelOptions(
            name='analytics_apps_systematic_trad',
            options={'verbose_name': 'Analytics Apps Systematic Trader', 'verbose_name_plural': 'Analytics Apps Systematic Trader'},
        ),
        migrations.AlterModelOptions(
            name='equity',
            options={'verbose_name': 'Equity Research', 'verbose_name_plural': 'Equity Research'},
        ),
        migrations.AlterModelOptions(
            name='learning',
            options={'verbose_name': 'Learning Center', 'verbose_name_plural': 'Learning Center'},
        ),
        migrations.AlterModelOptions(
            name='listpage',
            options={'verbose_name': 'List Main Pages', 'verbose_name_plural': 'List Main Pages'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'Market', 'verbose_name_plural': 'Market'},
        ),
        migrations.AlterModelOptions(
            name='money_making_investing',
            options={'verbose_name': 'Money Making Investing', 'verbose_name_plural': 'Money Making Investing'},
        ),
        migrations.AlterModelOptions(
            name='money_making_trading',
            options={'verbose_name': 'Money Making Trading', 'verbose_name_plural': 'Money Making Trading'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Subscribers List', 'verbose_name_plural': 'Subscribers List'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='Total_assets',
            new_name='Total_Assets',
        ),
        migrations.RemoveField(
            model_name='money_making_investing',
            name='Private_Public',
        ),
        migrations.AddField(
            model_name='money_making_investing',
            name='Equity_Type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
