# Generated by Django 3.2.6 on 2022-01-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20210910_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Brand',
            new_name='Clickable',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Name',
            new_name='Platform',
        ),
    ]
