# Generated by Django 3.2.6 on 2022-01-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20220126_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='Category',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='SubCategory',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='url',
            new_name='Research',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='Youtube',
            new_name='YouTube',
        ),
    ]
