# Generated by Django 3.2.6 on 2022-01-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20220126_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equity',
            old_name='Equity_Type',
            new_name='Market',
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='url',
            new_name='Research',
        ),
    ]
