# Generated by Django 3.2.6 on 2022-01-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20220126_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='Class',
            new_name='FileName',
        ),
    ]
