# Generated by Django 3.2.6 on 2022-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_learning_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='Product',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
    ]
