# Generated by Django 3.2.6 on 2022-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20220129_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_making_trading',
            name='Product',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
