# Generated by Django 3.2.6 on 2022-01-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_money_making_trading_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_making_investing',
            name='Initial_Inv',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='money_making_investing',
            name='Market',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='money_making_investing',
            name='Outcome',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='money_making_investing',
            name='Product',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='money_making_investing',
            name='ROI',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='money_making_investing',
            name='ReCap',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='money_making_investing',
            name='Ticker',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
