# Generated by Django 3.2.6 on 2022-01-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20220129_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='Description',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='equity',
            name='Product',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
