# Generated by Django 3.2.6 on 2022-01-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20220129_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sentence', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Social Networks',
                'verbose_name_plural': 'Social Networks',
            },
        ),
    ]
