# Generated by Django 3.2.6 on 2022-02-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_rename_clickable_table_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social_network',
            options={'verbose_name': 'Social Network', 'verbose_name_plural': 'Social Network'},
        ),
        migrations.AddField(
            model_name='learning',
            name='Description',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
