# Generated by Django 3.2.6 on 2022-02-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20220204_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money_making_trading',
            old_name='Date',
            new_name='TradeDate',
        ),
    ]
