# Generated by Django 3.2.6 on 2022-02-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_rename_date_money_making_trading_tradedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money_making_trading',
            old_name='TradeDate',
            new_name='Trade_Date',
        ),
    ]
