# Generated by Django 3.2.6 on 2022-02-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_rename_tradedate_money_making_trading_trade_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money_making_investing',
            old_name='Entry',
            new_name='Entry_Date',
        ),
        migrations.RenameField(
            model_name='money_making_investing',
            old_name='Exit',
            new_name='Exit_Date',
        ),
        migrations.RenameField(
            model_name='money_making_investing',
            old_name='Full_Name',
            new_name='Name',
        ),
    ]
