# Generated by Django 3.2.6 on 2022-02-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20220204_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='Date_Language',
        ),
        migrations.RemoveField(
            model_name='market',
            name='FileName',
        ),
        migrations.RemoveField(
            model_name='market',
            name='Region',
        ),
    ]
