# Generated by Django 3.2.6 on 2022-02-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20220205_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equity',
            name='ADV_10d',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Beta',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='ClosePrice',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Float',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Founded',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Industry',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Insider_Shares',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Market_Cap',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Net_income',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Outstanding_Shares',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Ticker_Date_Language',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Total_Assets',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='Website',
        ),
    ]
