# Generated by Django 3.2.6 on 2022-02-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20220205_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='Date_Category_Language',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='FileName',
        ),
    ]
