# Generated by Django 3.2.6 on 2022-02-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20220205_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money_making_trading',
            name='Date_Play',
        ),
        migrations.RemoveField(
            model_name='money_making_trading',
            name='Expiration_Date',
        ),
        migrations.RemoveField(
            model_name='money_making_trading',
            name='Plan',
        ),
        migrations.RemoveField(
            model_name='money_making_trading',
            name='Play',
        ),
    ]
