# Generated by Django 3.2.6 on 2022-02-05 06:46

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20220205_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money_making_trading',
            name='url',
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='ReCap',
            field=models.FileField(upload_to=base.models.path_money_making_trading),
        ),
    ]
