# Generated by Django 3.2.6 on 2022-02-05 06:57

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20220205_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money_making_investing',
            name='Equity_Type',
        ),
        migrations.RemoveField(
            model_name='money_making_investing',
            name='Strategy',
        ),
        migrations.RemoveField(
            model_name='money_making_investing',
            name='url',
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='ReCap',
            field=models.FileField(upload_to=base.models.path_money_making_investing),
        ),
    ]
