# Generated by Django 3.2.6 on 2022-02-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20220205_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='analytics_apps_systematic_trad',
            new_name='analytics_apps_Algo_trader',
        ),
        migrations.AlterModelOptions(
            name='analytics_apps_algo_trader',
            options={'verbose_name': 'Analytics Apps Algo Trader', 'verbose_name_plural': 'Analytics Apps Algo Trader'},
        ),
        migrations.AlterModelOptions(
            name='listpage',
            options={'verbose_name': 'Page List', 'verbose_name_plural': 'Page List'},
        ),
    ]
