# Generated by Django 3.2.6 on 2022-02-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_market_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
