# Generated by Django 3.2.6 on 2022-02-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_table_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analytical_apps_algo_trader',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analytical_apps_market_mover',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analytical_apps_prospecting',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analytical_apps_trade_ideas',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equity',
            name='Language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
