# Generated by Django 3.2.6 on 2022-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_auto_20220209_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='Language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='Language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='newslettersubscribe',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='social_network',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
