# Generated by Django 3.2.6 on 2022-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20220209_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equity',
            name='Institutional_Shares',
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Exit_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
