# Generated by Django 3.2.6 on 2022-02-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20220210_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'News Letter', 'verbose_name_plural': 'News Letter'},
        ),
    ]
