# Generated by Django 3.2.6 on 2022-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'NewsLetter', 'verbose_name_plural': 'NewsLetter'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscribe',
            options={'verbose_name': 'News Letter Subscribe', 'verbose_name_plural': 'News Letter Subscribe'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='phone',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='newslettersubscribe',
            old_name='language',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newslettersubscribe',
            name='Sentence',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='Sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newslettersubscribe',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='newslettersubscribe',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
