# Generated by Django 3.2.6 on 2022-02-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_alter_newsletter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'NewsLetter Subscribers',
                'verbose_name_plural': 'NewsLetter Subscribers',
            },
        ),
        migrations.DeleteModel(
            name='NewsLetterSubscribe',
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'NewsLetter', 'verbose_name_plural': 'NewsLetter'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='phone',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='name',
        ),
        migrations.AddField(
            model_name='equity',
            name='chk_field_name',
            field=models.FilePathField(null=True, path='C:/Users/SHAN/Desktop/Working'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='Sentence',
            field=models.TextField(blank=True),
        ),
    ]
