# Generated by Django 3.2.6 on 2022-02-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20220215_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equity',
            name='chk_field_name',
        ),
    ]
