# Generated by Django 3.2.6 on 2022-02-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20220210_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterSubscribe',
            new_name='NewsLetterSubscribers',
        ),
        migrations.AlterModelOptions(
            name='newslettersubscribers',
            options={'verbose_name': 'NewsLetter Subscribers', 'verbose_name_plural': 'NewsLetter Subscribers'},
        ),
    ]
