# Generated by Django 3.2.6 on 2022-02-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_remove_equity_chk_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpage',
            name='Priority',
            field=models.IntegerField(default=0),
        ),
    ]
