# Generated by Django 3.2.6 on 2022-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_listpage_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_making_investing',
            name='Initial_Inv',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_investing',
            name='Outcome',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Initial_Inv',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money_making_trading',
            name='Outcome',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
