# Generated by Django 4.0.1 on 2022-01-14 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMenthod', models.CharField(max_length=150)),
                ('customer_Id', models.CharField(max_length=150)),
                ('subscription_ID', models.CharField(max_length=150)),
                ('verification_id', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Stripe Verification Session ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
