# Generated by Django 3.2.6 on 2022-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_onetimepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
